# Worker Configuration
name = "notion-d1-worker"
main = "src/index.ts"
compatibility_date = "2024-03-21"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "notion-posts"
database_id = "c639cd89-4017-4bda-bb9f-46befa035be4"

# R2 Bucket Configuration
[[r2_buckets]]
binding = "R2"
bucket_name = "blog-data"

# Cron Trigger Configuration
[triggers]
# Schedule:
# - Sync: Daily at 5:00 AM UTC (syncs Notion posts to D1)
# - Extended Data: Daily at 5:30 AM UTC (generates AI summaries, tags, reading time)
# - Image Collection: Daily at 6:00 AM UTC (collects generated images)
crons = [
    "0 5 * * *",  # Sync workflow
    "30 5 * * *", # Extended data workflow
    "0 6 * * *"   # Image collection workflow
]

# Observability Settings
[observability]
enabled = true

# Environment Variables (Non-Sensitive)
[vars]
# Set in Cloudflare dashboard or use `wrangler secret put`
NOTION_ROOT_PAGE_ID = "1ab7ef86-a5ad-81ab-a4cb-f8b8f37ec491"

# Required Secrets (DO NOT SET HERE)
# Use `wrangler secret put` to set these secrets:
# ```bash
# # Notion API Configuration
# wrangler secret put NOTION_TOKEN
# wrangler secret put NOTION_DATABASE_ID
#
# # AI Service Configuration
# wrangler secret put DASHSCOPE_API_KEY  # For image generation
# wrangler secret put DEEPSEEK_API_KEY   # For text generation
# ```
#
# For local development:
# 1. Copy .dev.vars.example to .dev.vars
# 2. Fill in your development credentials
# 3. Use `wrangler dev` to run locally