# Worker Configuration
name = "notion-d1-worker"
main = "src/index.ts"
compatibility_date = "2024-03-21"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "notion-posts"
database_id = "c639cd89-4017-4bda-bb9f-46befa035be4"

# Cron Trigger Configuration
[triggers]
# Main sync runs at 5 AM UTC
# Image collection runs at 5:30 AM UTC to allow time for image generation
crons = ["0 5 * * *", "30 5 * * *"]

[observability]
enabled = true

# Environment Variables
[vars]
# Set in Cloudflare dashboard or use `wrangler secret put`
NOTION_ROOT_PAGE_ID = "1ab7ef86-a5ad-81ab-a4cb-f8b8f37ec491"

# Secrets (Do not set here)
# Use `wrangler secret put NOTION_TOKEN` to set your Notion API token securely 